### PR TITLE
Fix error in Safari with "use strict"

### PR DESCRIPTION
**Pull request by leedorian**
When using in Safari, got error:

`SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.`

This because the "callPrint" function is declared in try catch statement.

### CODE REVIEW

**Comment by sathvikp** [comment]
Thank you for taking the time and effort for this PR.
Do you think we could have it work while keeping the `"use strict";` declaration?
What version of Safari are you on?

**Comment by leedorian** [comment]
I did some changes on "callPrint" function, make it work in Safari when keeping the "use strict", and committed the merge request, please check.

**Comment by sathvikp** [comment]
That sounds good.
The commit seems to be missing though, could you please check?

Thanks!

**Comment by sathvikp** [comment]
Went with @3kthor3adward's #64 as it's simpler.
Thanks anyways @leedorian

**Pull request closed without merging**
